# db 생성 및 수정 필수!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodmap?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.foodmap.domain